apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: k8s-microservices-poc
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: k8s-microservices-poc
    app.kubernetes.io/managed-by: kubectl
  name: "frontend"
  namespace: "default"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: frontend
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: "frontend"
          servicePort: 8080

