apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
spec:
  type: LoadBalancer
  selector:
    app: orders
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
status:
  loadBalancer: {}
