apiVersion: apps/v1
kind: Deployment
metadata:
  name: "products-deployment"
  namespace: "default"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "products"
  template:
    metadata:
      labels:
        app: "products"
    spec:
      containers:
      - image: 535882074894.dkr.ecr.us-east-1.amazonaws.com/k8s-microservices-poc/products:v1
        imagePullPolicy: Always
        name: "products"
        ports:
        - containerPort: 8081
