apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: 535882074894.dkr.ecr.us-east-1.amazonaws.com/k8s-microservices-poc/products:v1
        name: products
        ports:
        - containerPort: 8081
